### ISSUE TITLE
swagger 배포 시 접속 불가하도록 비활성화

### ISSUE THREAD

**Issue by GiYeons** [In3ight/backend#37]

**Comment by songjaeheon** [comment]
property에 다음 설정 추가하면 비활성화됨

### disable OenAPI(swagger-ui)
springdoc.api-docs.enabled=false

[[How to disable swagger 3 configuration in spring boot](https://stackoverflow.com/questions/58183214/how-to-disable-swagger-3-configuration-in-spring-boot)]

**Comment by songjaeheon** [comment]
위 설정으로 AWS 배포 시에 오작동 확인
